# BS and PNL dictionary
di = {'Cash in NBU cash and BM': 0, 'Cash': 0, 'BM': 0, 'NBU until call': 0, 'NBU due': 0, 'FOP': 0,
      'VP NBU': 0, 'Trade VP NBU': 0, 'For sale VP NBU': 0, 'Due to payment VP NBU': 0, 'Issue NBU': 0,
      'Provisions VP NBU': 0, 'Interbank': 0, 'Until request': 0, 'Overnight': 0, 'S/T interbank': 0,
      'L/T interbank': 0, 'Overdue interbank': 0, 'Provisions interbank': 0, 'Trade portfolio (FV)': 0,
      'Portfolio for sale': 0, 'Portfolio-brutto': 0, 'Provisions (Portfolio for sale)': 0, 'Loans:': 0,
      'Legal entities loans': 0, 'bills factoring repo (loans to l/e)': 0, 'corporate purposes (loans to l/e)': 0,
      'investment loans (loans to l/e)': 0, 'mortgage loans to l/e': 0, 'overdrafts to l/e': 0, 'municipality loans': 0,
      'overdue/devaluated loans to l/e': 0, 'Private individ loans': 0, 'consumer loans PI': 0, 'mortgage PI': 0,
      'overdraft PI': 0, 'to investments activity': 0, 'overdue/devaluated PI': 0, 'provisions PI loans': 0,
      'VP due to repayment': 0, 'portfolio brutto VP': 0, 'provisions VP': 0, 'Investments to sub and associates': 0,
      'Main assets': 0, 'Intangibles': 0, 'Accrued income':0, 'MBK AI': 0, 'VP AI': 0, 'LE AI': 0, 'PI AI': 0,
      'overdue income AI': 0, 'overdue income2 AI': 0, 'provisions AI': 0, 'Deferred tax': 0, 'Others assets': 0,
      'account payables': 0, 'other assets': 0, 'provisions other assets': 0, 'LT asset for sale': 0, 'TOTAL ASSETS': 0,
      'Interbank obl': 0,'until call interbank': 0, 'overnight interbank': 0, 'short term lbl interbank': 0,
      'long term lbl interbank': 0, 'overdue liability interbank': 0, 'Funds of LegEnt:':0, 'due le:': 0,
      'due funds of LE': 0, 'due funds state sector LE': 0, 'until call:': 0, 'until call funds LE': 0,
      'until call funds state sector LE': 0, 'until political parties LE': 0, 'Funds of PrInd:': 0, 'due funds PI': 0,
      'until call funds PI': 0, 'Savings certificates': 0, 'Debt value papers': 0, 'Accrued Expenses': 0,
      'MBK accrued exp': 0, 'clients accrued exp': 0, 'VP accrued exp': 0, 'others accrued expenses': 0,
      'Deferred tax liability': 0, 'Others Liabilities': 0, 'unregistered charter': 0, 'dividends': 0,
      'others other liabilities': 0, 'LIABILITIES': 0, 'Subordinated debt': 0, 'Charter': 0,
      'Own shares': 0, 'emission differences': 0, 'reserves cap divid and funds': 0, 'Reserves reval MA': 0,
      'real estate reeval': 0, 'intangibles reeval': 0, 'VP reevaluation': 0, 'Last year result': 0,
      'This year result': 0, 'EQUITY': 0, 'TOTAL LIABILITIES': 0,
      'Net % Income': 0, '% Income:': 0, '% MBK income': 0, '% income LE': 0, '% income PI': 0,
      '% income others': 0, 'Net % Expenses': 0, '% MBK expenses': 0, '% LE expenses': 0, '% PI expenses': 0,
      '% other expenses': 0, 'Net Comiss Income': 0, 'commission income': 0, 'commission expenses': 0,
      'Trade Income': 0, 'VP_income': 0, 'currency and BM income': 0, 'Dividends income': 0, 'Capital income': 0,
      'Other incomes': 0, 'Non % income':0, 'Total incomes': 0, 'Administrative expenses': 0, 'Personnel expenses': 0,
      'Losses on shares in capital': 0, 'Others expenses': 0, 'Operational Income': 0, 'Loss on provisions': 0,
      'Profit before tax': 0, 'Profit tax': 0, 'Net Profit': 0}
